### ISSUE TITLE
Regexr simply doesn't work anymore

### ISSUE THREAD

**Issue by bgarrison25** [gskinner/regexr#111]
http://www.awesomescreenshot.com/image/616897/26a6371c068b648c4ac6a237e30481ca

The app now crashes in all browsers. The input text box at the top doesn't show and most links are broken. I have cleared everything / removed all plugins / tested in multiple browsers and it still does not work.

**Comment by gskinner** [comment]
All of the cast_sender.js errors are due to the embedded youtube video and can be ignored.

What looks like is happening, is for some reason you are unable to load the Google fonts, and this is blocking the rest of initialization. I'm not able to duplicate here, and I haven't gotten any other reports of problems, so it seems like it might be something related to your network or system, though I'm honestly not sure what the cause would be.

However, we should look at handling font loading errors better, and ensure a usable state even when fonts fail to load. I _think_ that should be a fairly easy fix. Feel free to take a stab at it and submit a pull request, or I'll take a look at it soon.

Thanks for the report!

**Comment by wdamien** [comment]
Related to #57

**Comment by dharma-guardian** [comment]
It was completely broken for me, too. I use the Ghostery Browser Extension, which blocks trackers and it blocked loading `http://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js`

**Comment by Nightfirecat** [comment]
@dharma-guardian See https://github.com/gskinner/regexr/issues/112#issuecomment-145186419.

**Comment by chrisivo** [comment]
+1 experiencing this. I need to block Google Fonts for work reasons (site load times when working offline etc). Would like to access RegExr without having to fiddle with my hosts file.

**Comment by wdamien** [comment]
I pushed an improved fallback to cover the case when the Google fonts script is blocked.  Now you should at-least see the default sans-serif, monospace fonts. Its live at http://regexr.com/  @bgarrison25  can you re-test? I was unable to directly reproduce your issue, but hopefully this fixes it.

**Comment by bgarrison25** [comment]
I am still getting the same issues. Here is the screenshot: http://tinypic.com/r/1086xpj/9

**Comment by wdamien** [comment]
@bgarrison25 sorry to hear your still having issues, I find it interesting your errors are coming from fonts.gstatic.com, and not ajax.googleapis.com. I will try reproduce this specific error locally, and hopefully I can track down a fix for you.

**Comment by wdamien** [comment]
@bgarrison25 I was able to reproduce your bug, and have pushed a fix up to RegExr.com. You will now see the default fonts when the google ones fail to load. It should go without saying, but you might need to clear your cache on your next visit.  Happy RegEx'ing!

**Comment by bgarrison25** [comment]
I have checked and it is in fact fixed. Thanks again!
